### ISSUE TITLE
Unexpected behavior for some Blocks

### ISSUE THREAD

**Issue by jonas089** [ethereum/eth-trie.rs#4]
```rust
        let memdb = Arc::new(MemoryDB::new(true));
        let mut trie = EthTrie::new(memdb.clone());


        for (index, tx) in block.transactions.iter().enumerate() {
            trie.insert(&alloy_rlp::encode(index), &tx.rlp())
                .expect("Failed to insert");
        }

        println!("transaction count: {}", block.transactions.len());

        let transaction_root = block.trjansactions_root;
        println!(
            "Expected Transaction Root: {:?}",
            &transaction_root.as_bytes()
        );
        let trie_root = trie.root_hash().unwrap();
        assert_eq!(trie_root, transaction_root);
```

I tested the above code with several blocks from Etherscan and sometimes it produces the correct root, but there are cases where it doesn't. For example, I tested with a Block that holds 187 transactions and with a Block that holds 121 transactions.

In the first case (187), I got an incorrect root hash for the transaction trie.
In the second case (121) I got a correct root hash for the transaction trie.

This indicates that there might be issues with the trie insertion or branching logic.

**Comment by KolbyML** [comment]
I would need the exact data used to replicate the bug. I have code using this library and it generated the correct state roots (and trandaction roots) for blocks 0-latest on Ethereum mainnet.

So I am not sure if this is a usage error or an edge case bug we are missing. But I would be happy to look into this with you and try to fix it!

**Comment by jonas089** [comment]
@KolbyML 

Full source can be found here (test_get_merkle_proof):
https://github.com/jonas089/sp1-eth-tx/blob/b4848b3ff15a322180e0bb1a82300bac99a258a5/rpc/src/lib.rs#L31

If you want to reproduce the issue, you can clone the repo and create a .env file with your infura mainnet key:

.env:
```
INFURA="YOUR_KEY"
```

then simply run the test:
```
cargo test test_get_merkle_proof
```

Currently it is set to use a block hash that works:
https://github.com/jonas089/sp1-eth-tx/blob/b4848b3ff15a322180e0bb1a82300bac99a258a5/rpc/src/lib.rs#L37

But there is a comment regarding a block hash that doesn't work:
```rust
        // works with
        let block_hash = "0x8230bd00f36e52e68dd4a46bfcddeceacbb689d808327f4c76dbdf8d33d58ca8";
        // does not work with
        // 0xfa2459292cc258e554940516cd4dc12beb058a5640d0c4f865aa106db0354dfa
```

The error can be reproduced by swapping the hashs and re-running the test.

**Comment by KolbyML** [comment]
@jonas089 hi Jonas I re-created the test case in our code. https://github.com/KolbyML/trin/commit/f87f426647ed69caf9a00b586bce6e60d1b64121 and I can confirm that we generate the correct transaction root using `eth-trie.rs`, so I am assuming the problem is your input's into the trie.


I also noticed you are using deprecated library's in your code for example `ethers` you should use `alloy` instead. You are also using `parity's` RLP library, those have been unmaintained for years, I recommend you use `alloy::rlp` it is much faster as well.

**Comment by jonas089** [comment]
I'm using alloy::rlp to encode the index already, no idea why it sometimes doesn't work. Can you find an issue in that test case that might explain why it works for you and doesn't work for me?

I use the deprecated libraries in other test cases only.

**Comment by KolbyML** [comment]
> I'm using alloy::rlp to encode the index already, no idea why it sometimes doesn't work. Can you find an issue in that test case that might explain why it works for you and doesn't work for me?
> 
> I use the deprecated libraries in other test cases only.

https://github.com/KolbyML/trin/commit/2e0eae65e1bc8358e9f20cfd1bf3f9d293f1c59a

I made the code match your's but using alloy::rlp instead

```rust
    let memdb = Arc::new(MemoryDB::new(true));
    let mut trie = EthTrie::new(memdb.clone());

    for (index, tx) in body.transactions().iter().enumerate() {
        let path = alloy::rlp::encode(index);
        let encoded_tx = alloy::rlp::encode(tx);
        trie.insert(&path, &encoded_tx).expect("Failed to insert");
        println!("index {}: {:?}", index, path);
    }

    let root_hash = trie.root_hash().expect("Failed to get root hash");
    assert_eq!(full_header.0.header.transactions_root, root_hash);
```

I am still getting the right result
so either
- your rlp library is giving you the wrong result
- you transactions input is incorrect

**Comment by KolbyML** [comment]
Ethers has been deprecated for quite some time so maybe it is returning you invalid transactions for blob transactions? Just a guess though as I didn't look through the ether results

**Comment by jonas089** [comment]
@KolbyML 
ethers_core::types::transaction::respotionse::Transaction

I see so maybe the rpl encoding of the transaction is wrong?

**Comment by jonas089** [comment]
@KolbyML what can I use instead of ethers to query the RPC?

**Comment by KolbyML** [comment]
> @KolbyML what can I use instead of ethers to query the RPC?

you can use `alloy`. `alloy` is the replacement for `ethers`

**Comment by jonas089** [comment]
```rust
        let block = provider
            .get_block_by_hash(
                B256::from_str(block_hash).unwrap(),
                alloy::rpc::types::BlockTransactionsKind::Full,
            )
            .await
            .expect("Failed to get Block!")
            .expect("Block not found!");

        let memdb = Arc::new(MemoryDB::new(true));
        let mut trie = EthTrie::new(memdb.clone());

        for (index, tx) in block.transactions.txns().enumerate() {
            println!("Transaction: {:?}", &tx);
            trie.insert(&alloy_rlp::encode(index), &alloy_rlp::encode(&tx.inner))
                .expect("Failed to insert");
        }
        let trie_root = trie.root_hash().unwrap();
        let expected_root = block.header.transactions_root;
        println!("Expected Root: {:?}", &expected_root);
        println!("Actual Root: {:?}", &trie_root);

        let tx_index = 0u64;
        let tx_key = tx_index.to_be_bytes();
```

trying with alloy now, but the roots don't yet match. am I incorrectly encoding the alloy Transaction object? e.g. tx.inner? @KolbyML

**Comment by KolbyML** [comment]
> ```rust
>         let block = provider
>             .get_block_by_hash(
>                 B256::from_str(block_hash).unwrap(),
>                 alloy::rpc::types::BlockTransactionsKind::Full,
>             )
>             .await
>             .expect("Failed to get Block!")
>             .expect("Block not found!");
> 
>         let memdb = Arc::new(MemoryDB::new(true));
>         let mut trie = EthTrie::new(memdb.clone());
> 
>         for (index, tx) in block.transactions.txns().enumerate() {
>             println!("Transaction: {:?}", &tx);
>             trie.insert(&alloy_rlp::encode(index), &alloy_rlp::encode(&tx.inner))
>                 .expect("Failed to insert");
>         }
>         let trie_root = trie.root_hash().unwrap();
>         let expected_root = block.header.transactions_root;
>         println!("Expected Root: {:?}", &expected_root);
>         println!("Actual Root: {:?}", &trie_root);
> 
>         let tx_index = 0u64;
>         let tx_key = tx_index.to_be_bytes();
> ```
> 
> trying with alloy now, but the roots don't yet match. am I incorrectly encoding the alloy Transaction object? e.g. tx.inner? @KolbyML

```rust
        let memdb = Arc::new(MemoryDB::new(true));
        let mut trie = EthTrie::new(memdb.clone());

        for (index, tx) in block.transactions.txns().enumerate() {
            let path = alloy_rlp::encode(index);
            let mut encoded_tx = vec![];
            match &tx.inner {
                // Legacy transactions have no difference between network and 2718
                TxEnvelope::Legacy(tx) => tx.eip2718_encode(&mut encoded_tx),
                TxEnvelope::Eip2930(tx) => {
                    tx.eip2718_encode(&mut encoded_tx);
                }
                TxEnvelope::Eip1559(tx) => {
                    tx.eip2718_encode(&mut encoded_tx);
                }
                TxEnvelope::Eip4844(tx) => {
                    tx.eip2718_encode(&mut encoded_tx);
                }
                TxEnvelope::Eip7702(tx) => {
                    tx.eip2718_encode(&mut encoded_tx);
                }
                _ => panic!("Unsupported transaction type"),
            }
            trie.insert(&path, &encoded_tx).expect("Failed to insert");
            println!(
                "index {:?}: {:?}",
                hex::encode(path),
                hex::encode(encoded_tx)
            );
        }
        let trie_root = trie.root_hash().unwrap();
        
```


Here is working code, the issue was that you weren't generating the RLP with the typed transaction prefixes aka EIP-2718

**Comment by jonas089** [comment]
@KolbyML Thank you so much, I just now figured that I was doing this wrong but decomposing the old library that I was looking at ended up being super painful. Your snipped helps me a lot :D.

Thanks 💯 🎉

**Comment by jonas089** [comment]
@KolbyML I'm trying to do the same for TransactionReceipts but it doesn't seem to be as straightforward, do you know how that's done?

```rust
        let memdb = Arc::new(MemoryDB::new(true));
        let trie = EthTrie::new(memdb.clone());
        for receipt in receipts {
            let inner: ReceiptEnvelope<alloy::rpc::types::Log> = receipt.inner;
            match inner {
                ReceiptEnvelope::Eip1559(r) => {}
                ReceiptEnvelope::Eip2930(_) => {}
                ReceiptEnvelope::Eip4844(_) => {}
                ReceiptEnvelope::Eip7702(_) => {}
                ReceiptEnvelope::Legacy(_) => {}
                _ => {}
            }
        }

```

here `r` is a ReceiptWithBloom<Log> but I can't call alloy_rlp::encode() on it :/.
